apiVersion: v1
kind: Service
metadata:
  name: svc-easyorder-app-client
spec:
  type: LoadBalancer
  selector:
    app: easyorder-app-client
  ports:
  - port: 80
    targetPort: 30000
    protocol: TCP
